name: Publish MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Mkdocs to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Install and run doxide
      - name: Add indii.org repository
        run: echo 'deb http://download.indii.org/deb focal main' | sudo tee /etc/apt/sources.list.d/indii.org.list
      - name: Add indii.org GPG key
        run: |
          curl -fsSL https://download.indii.org/deb/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/indii.org.gpg > /dev/null
      - name: Update APT package index
        run: sudo apt update
      - name: Install Doxide
        run: sudo apt install -y doxide
      - name: Run Doxide
        run: doxide build

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Copy notebooks into docs
        run: cp -r notebooks/* docs/ | echo "No notebooks found"
      - name: Deploy Mkdocs
        run: mkdocs gh-deploy --force